dashevo/dashmate

docker-compose.yml

Specifying options in the command causes dashd to start without loading the dash.conf file, even if it is in the default location.

fix: explicitly load conf file

---

README.md

Docs only updated to address issues #10 and #32 (close on merge)

docs: update README.md to clarify install instructions

---

src/commands/register.js
src/core/startCoreFactory.js

`mn register testnet [args]` failed at `Check funding address balance` with the error `No information available for address` when using a new funding privkey after the blockchain data had already been downloaded. This fix ensures it is always possible to check the balance of an address when registering a masternode.

fix: unavailable balance info during testnet registration

---

src/commands/reset.js

See https://github.com/dashevo/mn-bootstrap/issues/53
Disabled reset Drive and Tendermint tasks for testnet preset.
Tested manually by running `mn reset testnet`
None

fix: reset command fails for testnet preset

---

docker-compose.yml

This switches the sentinel image from my personal repo to the dashpay organizational repo, now that I have gained access.
Rebuilt image from organizational repos. The actual image content is identical.
Started a full node, verified sentinel started up properly, entered the running container and verified sentinel<-->core communication was working as expected.
None

fix: switch to dashpay org for sentinel

---

src/commands/start.js

Using drive or dapi build image path option caused a fatal error
Fixed issue
Run bootstrap in different configs
No

fix: using drive or dapi build image path option caused a fatal error

---

configs/evonet/dapi/nginx/default.conf
configs/evonet/dapi/nginx/grpc.conf
configs/local/dapi/nginx/default.conf
configs/local/dapi/nginx/grpc.conf

DAPI rate limits disabled for evonet and enabled for local for some reason
Disable rate limits for local and enable for evonet presets in DAPI Nginx configs
None
Evonet will limit requests for JSON RPC and gRPC Web

fix!: rate limits disabled for evonet and enabled for local

---

README.md
src/commands/start.js
src/docker/DockerCompose.js

Implements #74:  pull option to update docker images before starting
Added `-u` flag to start command to pull image updates before proceeding with start.
I think I have implemented this properly, but I'm unsure how to test it. What use case does it fix? Are devs changing version numbers in the .env files before running the start command, wouldn't this force a pull already? Which images can I use for testing?

feat: implement `update` option for `start` command

---

docker-compose.platform.build-dapi.yml
docker-compose.platform.build-drive.yml

Docker does not know about `dapi:local` and `drive:local` images upon first run
Use only `build` instructions
Local dev env.
None.

fix: missing `build` section for `tx_filter_stream_service` service

---

docker-compose.platform.yml

Fixing missing env vars
Added `TENDERMINT_HOST` and `TENDERMINT_PORT` vars
Local dev env.
None.

fix: missing env variables for `dapi-tx-filter-stream` service

---

configs/evonet/core/dashd.conf

Bumps evonet version to match the version currently deployed on the network. Resolves the following error on core startup:
`
2020-07-24 00:36:50 connected to wrong devnet. Reported version is /Dash Core:0.15.0(devnet=devnet-evonet-5)/, expected devnet name is devnet-evonet-4
`
Increment version number
Ran `mn start evonet <...>` and it worked

fix: bump evonet version

---

configs/evonet/dapi/envoy/grpc.yaml
configs/local/dapi/envoy/grpc.yaml

Transaction filter stream doesn't work with gRPC-Web clients
Fixed wrong address for Transaction filter stream service in Envoy config
With tests
None

fix: transaction filter stream doesn't work with gRPC-Web

---

src/config/systemConfigs/systemConfigs.js

Fixes a typo introduced in #119 
This typo was prevent abci from syncing and causing tendermint to crash

fix: typo in dpns ownerId

---

docker-compose.platform.yml
docker-compose.yml
src/config/configJsonSchema.js
src/config/systemConfigs/systemConfigs.js

Combines image and tag in single field, as requested [here](https://github.com/dashevo/mn-bootstrap/pull/124#discussion_r477500563).
Tags are optional and do not follow any firm convention, making them hard to validate. This commit changes internal handling of tags to align with how Docker does things.

feat: combine image and tag in single field

---

configs/local/drive/tendermint/config.toml

For the local network, we do not provide `genesis.json` which should be dynamically generated by `tendermint int` command from docker compose config. So we need to move this file to tendermint data volume to make it writeable for tendermint.
`genesis.json` is set to writable `data` dir.
With running `mn setup-for-local-development`
None

fix: can't generate genesis config for local

---

package.json
src/commands/start.js
src/config/configJsonSchema.js
src/config/systemConfigs/systemConfigs.js
src/docker/DockerCompose.js

In order to avoid mining manually during tests and development with a local  node, we should introduce an option for the node start command  that will start miner script if present.
Added a new option `mine-blocks` for the `start` command
None

feat: new option for block mining with local config

---

docker-compose.platform.yml

Set `config` dir read only to prevent accidentally writing mutable state.
It is not possible to bind-mount the config files directly in `docker-compose.platform.yml` because not all configs provide a `genesis.json` file. Also the `~/config` directory does not exist in the Docker image, which would result in creation of the config dir as root. However, it is still important not to write mutable data to this directory. This PR ensures that the config dir is read-only.
Add `:ro` flag to bind mount instruction.
Started masternode and attempted to reproduce the bug fixed in #140 . Masternode startup fails with logs showing the error `ERROR: open /tendermint/config/genesis.json: read-only file system`

fix: set config bind mount read-only

---

src/commands/config/envs.js

Removes quotes from generated .env file, since these are not handled by docker-compose.
Trying to start a node with `mn config:envs -o .env && docker-compose up` fails with various errors as follows:
```
services.core.ports contains an invalid type, it should be a number, or an object
ERROR: .FileNotFoundError: [Errno 2] No such file or directory: './"docker-compose.yml"'
```
According to the [env file spec](https://docs.docker.com/compose/env-file/):
- There is no special handling of quotation marks. This means that **they are part of the VAL.**
Remove quotes from generated output.
`mn config:envs -o .env && docker-compose up`
--> no errors, services start as expected

fix: services.core.ports contains an invalid type

---

configs/evonet/core/dashd.conf
configs/local/core/dashd.conf

This PR is a fix to support new behaviour in Dash 0.16, which includes a [backport](https://github.com/dashpay/dash/commit/b0dc2ab3c1) of [bitcoin#11862](https://github.com/bitcoin/bitcoin/pull/11862) which breaks certain conf statements if they are not in the correct section.
This fixes the following error:
```
2020-10-08 04:03:21 Dash Core version v0.16.0.1
2020-10-08 04:03:21 InitParameterInteraction: parameter interaction: -externalip set -> setting -discover=0
2020-10-08 04:03:21 InitParameterInteraction: parameter interaction: -whitelistforcerelay=1 -> setting -whitelistrelay=1
2020-10-08 04:03:21 InitParameterInteraction: parameter interaction: additional indexes -> setting -checklevel=4
2020-10-08 04:03:21 Warning: Config setting for -addnode only applied on devnet network when in …
```

fix: use conf sections in dash.conf

---

README.md
src/commands/restart.js
src/commands/setup-for-local-development.js
src/commands/start.js
src/config/configJsonSchema.js
src/config/systemConfigs/systemConfigs.js
src/listr/tasks/startNodeTaskFactory.js

This PR implements the `restart` command described in #68 
Now that the config command was implemented in #119, the config state is stored on disk. This allows us to restart a node with a single command, running updated code or config on restart.
My approach here was just to combine the stop and start commands in a single new command. Oclif allows you to [call commands programmatically](https://oclif.io/docs/running_programmatically), but I'm not sure if this is a good idea here, given we would just be passing the same arguments around anyway. 

feat: restart command

---

package-lock.json
src/listr/tasks/platform/initTaskFactory.js

`cannot read property ‘isDocumentDefined’ of null` error is throwing due to using old way to define application. 
Used new `Client#getApps#set` methods chain.
None
None

fix: cannot read property ‘isDocumentDefined’ of null

---

README.md

Fix incorrect docs raised in #169 
It is not possible to mint Dash on evonet. Docs need updating to reflect this.
Remove docs indicating mint works on evonet

docs: cannot mint dash on evonet

---

configs/testnet/core/dashd.conf

Sentinel could not connect on testnet due to update to Dash Core 0.16 with different `dash.conf` format
RPC was not configured properly
Move RPC conf details into `[test]` section
`mn start` with testnet conf works, sentinel container is not restarting and showing results from Core RPC
none

fix: use conf sections for testnet

---

src/config/configJsonSchema.js
src/config/systemConfigs/systemConfigs.js
templates/default.conf.template
templates/grpc.conf.template

This PR adds the nginx rate limiter to the config template.
Resolves #182. Prior to use of templates, the local config did not enable the nginx rate limiter config. This was accidentally re-enabled in the templates, causing errors during testing. This PR allows the user to configure the rate limiter, and ensures it is off by default on in the local config.
Add enabled/rate/burst to config and nginx templates.
None

feat: implement rate limiter in config

---

src/config/systemConfigs/systemConfigs.js

Updates envoy version to 1.16, the first release to officially support ARM architecture.
This updates envoy to a version with ARM support so we can begin to support the evo stack on devices like Raspberry Pi or AWS Graviton2.
Bump envoy version
Tested locally to see if anything fails to load, everything seems fine. Envoy logs contain a few new messages about deprecated config syntax, in addition to a few deprecation notices that were already present in 1.14 logs. I can try to fix this, or someone with a better understanding of what envoy is doing in the evo stack could do it instead.
None

feat: update envoy for multi-arch support

---

templates/default.conf.template

Fix syntax error introduced in #183 
nginx was restarting with following error:
```
2020/12/10 20:59:13 [emerg] 1#1: invalid rate "rate=120/m" in /etc/nginx/conf.d/default.conf:1
nginx: [emerg] invalid rate "rate=120/m" in /etc/nginx/conf.d/default.conf:1
```
Added missing "r" to rate limit
Tested on evonet, nginx no longer throws error
None

fix: syntax error in nginx config

---

package-lock.json
templates/dashd.conf.template

Drive requires `rawchainlocksig` zmq socket instead of `rawchainlock`. DAPI requires `zmqpubrawtxlocksig`
Expose `rawchainlocksig` and `zmqpubrawtxlocksig` in dashd config instead of `rawchainlock`
Run setup for local development command
None

feat: expose `rawchainlocksig` and `zmqpubrawtxlocksig` from Core

---

src/config/configJsonSchema.js
src/config/systemConfigs/systemConfigs.js
src/listr/tasks/platform/initTaskFactory.js

With the local network there is no instant lock quorums atm, so we use fallbacks in Drive and need to pass fake instant lock messages. 
Introduced `platform.drive.passFakeAssetLockProofForTests` option which is enabled for local config.
None
`platform.drive.passFakeAssetLockProofForTests` option is required.

feat!: configure `passFakeAssetLockProofForTests`

---

package-lock.json
src/commands/setup.js
src/commands/status/index.js
src/commands/status/platform.js
src/listr/tasks/platform/initTaskFactory.js
src/templates/renderServiceTemplatesFactory.js
src/templates/writeServiceConfigsFactory.js

Fixes several errors and crashes relating to rmdir errors and tendermint -> tenderdash renaming. Also adds a version number when running `dashman setup`.
Fixes:
- multiple errors relating to tendermint/tenderdash renaming
- error if tenderdash up but not responding due to abci error
- `dashman config` was failing with the following errors: 
- `✖ ENOENT: no such file or directory, rmdir '/home/strophy/.dashman/testnet'`
- `    Error: ENOTEMPTY: directory not empty, rmdir '/home/strophy/.dashman/testnet'`
- rename tendermint -> tenderdash
- try/catch when calling tenderdash status
- switch to rimraf
- add version number
- linting
Tested locally

fix: rmdir and tenderdash errors

---

src/commands/status/index.js
src/commands/status/platform.js

improved checking and catching of errors when nodes might not respond
This PR prevents errors when querying nodes which might not be able to respond yet
wrap query functions in try/catch syntax
Tested together with other PRs

fix: handle node down errors in status command

---

src/commands/status/core.js
src/commands/status/index.js
src/commands/status/platform.js

Catches errors and substitutes sensible defaults instead.
mn was crashing when insight, tenderdash or mnowatch were not available.
Catch previously uncaught errors and substitute sensible defaults instead.
Tested locally and on testnet masternode while syncing.
None

fix: uncaught errors when remote services down

---

src/commands/status/index.js

Fix unsafely using potentially blank variable in fetch command.
Running `mn status` on testnet resulted in: `TypeError: Only absolute URLs are supported`
Check variable is not blank before running query
On testnet, no longer throws error

fix: status command returns TypeError

---

src/config/systemConfigs/systemConfigs.js

Bump core image version to 0.17.0.0-rc3
Community members have been using mn-bootstrap to set up masternodes, but the older version can no longer sync completely. This PR saves them time wasted syncing with the wrong client version by setting the right client version to start with.
Bump core image version to 0.17.0.0-rc3
Started with no config dir and started node, installed version is 0.17-rc3

feat: bump core version to 0.17-rc3

---

templates/dashd.conf.template

llmq-qvvec-sync is used to synchronise quorum verification vectors
Masternodes not deployed by the deploy tool do not contain this setting
Add `llmq-qvvec-sync=llmq_100_67` to testnet dash.conf
Started testnet node, sync is included in file and core does not crash.

feat: enable llmq-qvvec-sync on testnet

---

docker-compose.yml
src/config/configJsonSchema.js
src/config/configOptionMigrations.js
src/config/systemConfigs/systemConfigs.js

This PR adds the Sentinel image version to config.
Sentinel is the only service not yet included and versioned in config. It should be in config so it can be updated independently to mn-bootstrap updates by users directly using `mn config:set`
Added `core.sentinel.docker.image` setting and upgrade rules.
I was unable to test upgrade rules since I'm still not sure how semver parses `-dev` suffixes, see discussion [here](https://github.com/dashevo/mn-bootstrap/pull/252#discussion_r568102141).

feat: include sentinel image version in config

---

src/commands/reset.js

Change async function to wait for promises to resolve before moving on to sync code.
Tenderdash was crashing after `mn reset --platform-only` because the Tenderdash volume was deleted, but not recreated. This was a sporadic problem, when the system was under load it did not occur.
Investigation showed the async function to get the docker container and remove it wasn't waiting for the promise to resolve before continuing. I think it is [this problem](https://stackoverflow.com/questions/37576685/using-async-await-with-a-foreach-loop). It works now, but I don't know why. It is almost certainly possible to improve this further using `Promise.all` or using proper chaining syntax.
Test multiple times with low system load, cannot reproduce the bug again.
**For repository code-owners and …

fix: reset function doesn't wait for volume to be removed

---

src/oclif/command/ConfigBaseCommand.js

Configs included in a group are not allowed to use with non-group commands
- Removed group assertion for config-required commands
Running commands
None

fix: grouped configs are not allowed to use

---

package-lock.json
package.json
src/core/activateCoreSpork.js
src/core/waitForCoreQuorum.js
src/createDIContainer.js
src/listr/tasks/resetNodeTaskFactory.js
src/listr/tasks/setup/local/activateSporksTaskFactory.js
src/listr/tasks/setup/local/configureCoreTaskFactory.js
src/listr/tasks/setup/local/initializePlatformTaskFactory.js
src/util/getSeedNodeConfig.js
src/util/isSeedNode.js
templates/dashd.conf.template

Added spork activation to local setup
No

feat: activate sporks during local setup

---

package-lock.json
src/commands/status/index.js
src/commands/status/platform.js

This PR fixes a display error in the `status` and `status:platform` commands now that an external block explorer is available.
The `status` and `status:platform` commands would show `Infinity%` remaining sync when no external source of the final platform block height was available.
Added a URL to an external platform block explorer (thanks cloudwheels for setting this up)
Tested while syncing platform on testnet.
Why did package-lock.json get updated? Does this break anything?

fix: platform sync shows Infinity%

---

src/commands/status/core.js
src/commands/status/masternode.js
src/config/Config.js
src/docker/DockerCompose.js
src/oclif/errors/MuteOneLineError.js

This PR allows mn-bootstrap to run on Windows if proper dependencies are installed.
New platform devs may be using Windows instead of unix-based systems and need an easy way to set up a local node for development purposes.
- Specify compose path separator to override default of `;` on windows
- Use regex instead of literal to detect end of line
Tested on Windows 10 and Ubuntu 20.10
None

fix: commands do not work on windows

---

src/commands/group/stop.js
src/core/waitForCoreQuorum.js
src/listr/tasks/platform/initTaskFactory.js
src/listr/tasks/setup/local/initializePlatformTaskFactory.js

Make mn-bootstrap to work without fake AS proofs
- removed `passFakeAssetLock` option 
- make services stop in reverse order to avoid mns getting banned
- increased quorums waiting to 2 quorums from 1

fix: make services stop in a reverse order to avoid nodes getting banned

---

src/commands/group/start.js
src/listr/tasks/setup/local/initializePlatformTaskFactory.js

`waitForNodeToBeReady` tasks were constructed in a wrong way
- Fixed
Local setup
None.

fix: waitForNodeToBeReady tasks were constructed in a wrong way

---

src/listr/tasks/setup/setupRegularPresetTaskFactory.js

This PR fixes a bug when registering a testnet masternode with a provided collateral private key.
`mn setup testnet masternode -p <privkey>` was failing with the "Register masternode" step not executing.
Return the listr object instead of waiting for it to complete. I'm not sure why this worked during development, and also not sure why this fixes it...
Tested on testnet

fix: cannot register testnet mn

---

docker-compose.platform.yml

Running local preset with drive network set to "testnet" results in crash when verifying instalocks

fix: drive network is always set to "testnet"

---

src/docker/DockerCompose.js

With docker-compose 1.29 container.inspect throws error if the container isn't running
Catch error thrown by `container.expect()` and if it's "no such container" error, return false, as container isn't running
None

fix: mn-bootstrap not working with docker-compose 1.29

---

src/core/waitForMasternodesSync.js
src/createDIContainer.js
src/listr/tasks/startNodeTaskFactory.js

If miner starts working before all masternodes are synched, a masternode could be banned.
New task to wait for masternodes to be synced before starting miner
No

fix: wait for masternodes to be synced before start miner

---

README.md
src/commands/setup.js
src/listr/tasks/setup/setupLocalPresetTaskFactory.js

Enable the core miner and set the interval for a network created with `setup local`
- Add flag to specify interval
- Add step to query mining interval if not specified
- Add basic validation (integer/decimal + `m` or `s` unit)
- Show default from base config
- Miner is now always enabled on seed node for all local configs (should this be optional?)
Tested with various values, network creates blocks with that duration
`setup local` command requests miner interval set

feat!: enable and request miner interval for setup local

---

src/listr/tasks/platform/waitForNodeToBeReadyTaskFactory.js

Sometimes the wait for nodes to be ready task complete before Tenderdash is actually caught up.
- Checked that Tenderdash is not catching up
Starting nodes with the `wait-for-readiness` option many times.
None

fix: wait nodes to be ready

---

src/listr/tasks/startGroupNodesTaskFactory.js

Mocktime not being adjusted properly in the bash script
Moved setting initial mock time outside of the bump cycle
Run the tests
None

fix: mocktime adjustement

---

bin/temporary_reset_script.sh

The reset script was aborting halfway through if the output of `$(docker ps -a -q)` was blank
- Allow `docker rm` command to exit with error and still continue
- Prune `system` instead of just `volumes` (also cleans up networks)
- Add `set -e` to stop script on all errors
Tested locally and by Discord user Sam8

fix: reset script aborts if no containers present

---

src/core/quorum/waitForQuorumConnections.js

We don't need to wait for all nodes in waitForQuorumConnections. This will never ends if we use > 3 nodes.
waitForQuorumConnections now waits for only 3 nodes
No

fix: waitForQuorumConnections stuck with more than 3 nodes

---

src/listr/tasks/platform/initTaskFactory.js

We don't need to pass waitForInstantLockTimeout option to Dash.Client anymore
Removed waitForInstantLockTimeout option from Dash.Client
No

revert: waitForInstantLockTimeout option from Dash.Client

---

templates/core/dash.conf.dot

LLMQ settings are necessary for devnets
- added `llmqchainlocks=llmq_devnet`
- added `llmqinstantsend=llmq_devnet`
In deploy tool
None

fix: missing llmq conf for devnets

---

configs/system/base.js
configs/system/testnet.js
docker-compose.platform.yml
src/listr/tasks/setup/setupLocalPresetTaskFactory.js
src/listr/tasks/startNodeTaskFactory.js

Local windows install fails on my machine. The issue is linked to the manual absolute path '/tmp/' used to write log files. 
- Used `os` node package to get tmp directory based on os in use. 
- Tested locally
None

fix: windows tmp directory install error

---

templates/platform/drive/tenderdash/config.toml.dot

Merk library is updated in Drive to a newer version. It uses the blake3 hashing algorithm that has 32 bytes hash size.
- Set `app_hash_size` to 32 bytes in Tenderdash config
Running `setup local` command
Drive with the previous version of Merk is not supported.

feat!: migrate Drive's state tree to blake3
