- data/bitcore-node-dash.json
- docker-compose.yaml
- presets/latest.env
please note that I did not try to fix compatibility with other version(porto/maithai) which by the way also do not work now.
if we need to support all these version as well, please let me know I'll fix them too.
> Update docker-compose config up to latest images

- docker-compose.yml
> fix: dash-cli doesn't work without default config

- README.md
The inappropriate header size for "reset data".
Changed h4 to h3 for the "reset data" section.
None
None
> docs: fix "reset data" header in README

- src/commands/register.js
Masternode list was empty after successful masternode registration
Wait for 1 confirmation after ProRegTx broadcasted.
Manually
No
> fix: ProRegTx is not confirm

- src/core/startCoreFactory.js
- src/core/waitForCoreStart.js
- src/docker/DockerCompose.js
On the first start, docker container name is incorrect
Fixed docker container output parsing
> fix: parsing docker container name on first start

- README.md
Add release version badge
Add GitHub release version badge and make badge style consistent
N/A
N/A
> docs: add version badge

- docker-compose.platform.yml
There is an issue with bad volumes mount points with original tendermint docker image.
Switched to tendermint docker image from dashpay dockerhub with fixed volumes paths
Started locally
None
> fix: original tendermint image creates wrong mount points

- package-lock.json
- package.json
Updated version to `0.14.0-dev.3`
Updated version to `0.14.0-dev.3`
Linter and tests.
None.
> chore: bump version to `0.14.0-dev.3`

- README.md
Add release-date badge to bring in compliance with other repos.
N/A
N/A
> docs: add release date badge

- src/listr/tasks/startNodeTaskFactory.js
.env file is trying to be included from the wrong directory
Fixed code that is trying to open .env file
Manually
None
> fix: .env file is trying to be included from the wrong directory

- package-lock.json
- package.json
- src/sdk/createClientWithFundedWallet.js
- src/sdk/fundAddress.js
- src/sdk/generateBlocksWithSDK.js
- src/sdk/getInputsByAddress.js
- src/sdk/waitForBlocksWithSDK.js
Updated DashJs to 3.14.0-dev.3. Fixed breaking changes.
Code is incompatible with DashJs lower then 3.14.0-dev.3.
> chore: update DashJs to 3.14.0-dev.3

- package-lock.json
- package.json
Update version
Version is `0.14.0-dev.5` now
Tests.
None.
> chore: bump version to 0.14.0-dev.5

- package-lock.json
- package.json
Update version
Updated version to `0.14.0-dev.6`
Tests.
None.
> chore: update version to 0.14.0-dev.6

- src/commands/platform/init.js
- src/commands/setup-for-local-development.js
- src/listr/tasks/platform/initTaskFactory.js
- src/sdk/createClientWithFundedWallet.js
platform:init was unused for events usage.
platform:init command has been changed to make work with any network.
By running all commands on local machine
platform:init command syntaxis has been changed.
> feat: platform:init can work with any network

- package.json
- src/commands/status/host.js
- src/commands/status/masternode.js
Minor issues in command output.
Adds a header row to commands where it was missing and fixes help output.
Ran locally
None
> refactor: status command output refactoring

- README.md
Add missing docs for status command
Describe command and include an example
Proofreading
None
> docs: document `status` command in README

- src/commands/setup-for-local-development.js
To make usage of setup-for-local-development command even more comfortable, we decided to add docker image update support option
Added docker image update support to setup-for-local-development command
Manually
None
> feat: add docker image update support to setup-for-local-development command

- configs/evonet/drive/tendermint/config.toml
- configs/local/drive/tendermint/config.toml
Due to `lastBlockHeaderTime` is for the last committed block, we should generate empty blocks within block window.
- Updated `Tendermint` config files to generate empty blocks
Local dev setup using `mn-bootstrap`
None.
> feat: generate empty blocks every 3 minutes

- package-lock.json
- package.json
Updated version for release
Updated version for release
None.
> chore: bump version to `0.15.0-dev.4`

- package-lock.json
- package.json
- src/listr/tasks/platform/initTaskFactory.js
Use new `DPNS` contract
Updated `dpns-contract`
None.
> feat: use new DPNS contract

- package-lock.json
- package.json
Updated version
Updated version
None.
> chore: bump version to `0.15.0-dev.5`

- configs/evonet/dapi/envoy/grpc.yaml
- configs/evonet/dapi/nginx/default.conf
- configs/evonet/dapi/nginx/grpc.conf
- configs/local/dapi/envoy/grpc.yaml
- configs/local/dapi/nginx/default.conf
- configs/local/dapi/nginx/grpc.conf
As we've moved `subscribeToTransactionsWithProofs` to `Core` we need to update configs
Updated `nginx` and `envoy` configs
> feat: move `subscribeToTransactionsWithProofs` to `Core` service

- package-lock.json
- package.json
Updated version for a release
Updated version for a release
> chore: update version to 0.15.0-dev.6

- package-lock.json
- package.json
Updated version
Updated version
> chore: bump version to 0.15.0-dev.8

- configs/evonet/dapi/nginx/default.conf
- configs/evonet/dapi/nginx/grpc.conf
- configs/local/dapi/nginx/default.conf
- configs/local/dapi/nginx/grpc.conf
Nginx should handle API requests for undefined versions. * To do so we need to add a location with wildcard instead of version and respond with UNIMPLEMENTED (12) gRPC status code.
Changed nginx configs
Manually
None
> feat: nginx responds with unimplemented in case if version is not supported

- src/config/systemConfigs/systemConfigs.js
Some of image versions were not updated in base config
Updated `drive` image to `0.15-dev`
> feat: update base config image versions

- package-lock.json
- package.json
Updated version
Updated version
> chore: bump version to 0.15.0-dev.9

- src/commands/wallet/mint.js
The `address` option is ignored for the `wallet:mint` command.
Fixed context property name.
Running the command with the `address` option manually.
None.
> fix: ignored mint address option

- package-lock.json
- package.json
Updated `dashjs` to latest dev release
Updated `dashjs` to latest dev release
> feat: update `dashjs` to 3.15.0-dev.3

- src/commands/setup-for-local-development.js
- src/listr/tasks/wallet/generateToAddressTaskFactory.js
We are generating blocks in order to confirm coinbase transactions in too many places  
Removed unnecessary block generation
With running `setup-for-local-development` and then running test suite the local it.
None
> feat: remove unnecessary block generation

- package-lock.json
- package.json
Bumped version
Unit tests
None
> chore: bump version to 0.15.0-dev.11

- package-lock.json
- package.json
- src/config/systemConfigs/systemConfigs.js
We need to update dashd
dashd updated to 0.16
@dashevo/dashd-rpc updated to 2.0.2
Tests
No
> feat: update dashd to 0.16

- package-lock.json
- package.json
Bumped version
Unit tests
None
> feat: bump version to 0.16.0-dev.1

- src/config/systemConfigs/systemConfigs.js
switched insight-api docker image
No
> feat: switch insight-api docker image to shumkov/insight-api:3.0.0

- package-lock.json
- package.json
Bumped version
Unit tests
None
> feat: bump version to 0.16.0-dev.2

- package-lock.json
- package.json
- src/listr/tasks/platform/initTaskFactory.js
Need to update code to be compatible with DPP 0.16-dev
dpns-contract, wallet-lib, dash were updated to the latest dev versions
Tests
Data from the previous version is not compatible with the current version. Please reset your data.
> feat!: update dpp to 0.16-dev

- package-lock.json
- package.json
Bumped version
Unit tests
None
> chore: bump version to 0.16.0-dev.3

- package-lock.json
- package.json
Bumped version
Unit tests
None
> chore: bump version to 0.16.0-dev.4

- package-lock.json
- package.json
Bumped version
Unit tests
None
> chore: bump version to 0.16.0-dev.6

- package-lock.json
- package.json
- src/config/systemConfigs/systemConfigs.js
> feat: update dependencies

- package-lock.json
- package.json
- src/config/systemConfigs/systemConfigs.js
Bumped version
Unit tests
None
> chore: bump version

- docker-compose.platform.yml
- src/config/configJsonSchema.js
- src/config/systemConfigs/systemConfigs.js
It useful for debugging need to have `NODE_ENV` and logging level configurable
Added `environment` and `platform.drive.abci.log.level` to config.
Run commands
None
> feat: make `NODE_ENV` and logging level configurable

- src/commands/setup-for-local-development.js
- src/listr/tasks/platform/initTaskFactory.js
- src/listr/tasks/startNodeTaskFactory.js
`platform:init` command can be runned against any network using the `seed` argument but block height obtain logic suppose to connect to Tendermint RPC that available only locally.
Skip "obtain DPNS block height" for any seeds and networks except "local"
Running `platform:init` command.
None.
> fix: can't obtain DPNS contract block height

- configs/evonet/core/dashd.conf
- configs/local/core/dashd.conf
- src/config/systemConfigs/systemConfigs.js
[Some required for Platform features](https://docs.google.com/document/d/1sJQ6gk9za3vaGTUg5hcn4HAFPBA8WszItsI_tKwb7VU/edit) are implemented in Dash Core develop branch.
Update Core to 0.17 dev branch.
Start node
> feat: update Core to 0.17 dev

- docker-compose.platform.yml
- docker-compose.yml
Drive zmq client needs to have host and port options.
Added CORE_ZMQ_HOST and CORE_ZMQ_PORT env variables to docker-compose file.
Manually
No
> feat: add ZMQ envs for Drive

- src/config/systemConfigs/systemConfigs.js
Updated dapi and drive docker images up to 0.17-dev
Manual
No
> feat: update dapi and drive docker images up to 0.17-dev

- package-lock.json
- package.json
- src/config/systemConfigs/systemConfigs.js
Bumped version
Unit tests
None
> feat: bump version to 0.17-dev.3

- src/commands/register.js
- src/commands/setup-for-local-development.js
Verbose mode added for register and setup-for-local-development commands
No
> feat: verbose mode for register and setup-for-local-development commands

- package-lock.json
- package.json
Bumped version
Unit tests
None
> feat: bump version to 0.17.0-dev.4

- package-lock.json
- package.json
Bumped version
Unit tests
None
> chore: bump version to 0.17.0-dev-5

- src/core/startCoreFactory.js
- src/docker/DockerCompose.js
- src/templates/writeServiceConfigs.js
- templates/dashd.conf.template
Fixed DashCore config and linter errors
Manually
No
> fix: lint errors and dash core config

- package-lock.json
- package.json
Bumped version
Unit tests
None
> chore: bump version to 0.17.0-dev.6

- package-lock.json
- package.json
Bumped version
Unit tests
None
> chore: bump version to 0.17.0-dev.7

- package-lock.json
- package.json
- src/listr/tasks/platform/initTaskFactory.js
This PR allow to register dashpay contract on init script execution.
- added dashpay-contract as a dependency
- register a identity for dashpay contract
- register dashpay contract
> feat: register dashpay contract

- package-lock.json
- package.json
> chore(release): mn-bootstrap 0.17.0-dev.8

- src/docker/DockerCompose.js
- src/templates/renderServiceTemplatesFactory.js
> fix: templates dir not found in travis

- package-lock.json
- package.json
Bumped version
Unit tests
None
> chore: bump version to 0.17.0-dev.9

- package-lock.json
- package.json
> chore: bump version to 0.17.0-dev.10

- src/config/systemConfigs/systemConfigs.js
Update Insight API to 3.1.0
Updated Insight docker image tag
None
None
> feat: update Insight API to 3.1.0

- src/config/systemConfigs/systemConfigs.js
Update Insight API to 3.1.1
Insight API docker image tag changed to 3.1.1
None
None
> feat: update Insight API to 3.1.1

- package-lock.json
- package.json
> chore(release): bump version to 0.17.0-dev.13

- package-lock.json
- package.json
bump version to 0.17.0-dev.14
bump version to 0.17.0-dev.14
> chore: bump version to 0.17.0-dev.14

- src/commands/setup-for-local-development.js
- src/oclif/command/BaseCommand.js
- src/tenderdash/initializeTenderdashNodeFactory.js
Running tenderdash init on every command causing some strange behaviour and inconsistency between configs and node data.
Moved tenderdash init to setup command.
Running commands
None
> fix: tenderdash init on every command causing problems

- package-lock.json
- package.json
bump version to 0.17.0-dev.15
bump version to 0.17.0-dev.15
None.
> chore: bump version to 0.17.0-dev.15

- package-lock.json
- package.json
bump version to 0.17.0-dev.16
bump version to 0.17.0-dev.16
> chore: bump version to 0.17.0-dev.16

- src/templates/writeServiceConfigsFactory.js
During writing configs, previous written are deleting
Clean config directory before write all configs
Running setup command
None
> fix: configs are removed during writing

- package-lock.json
- package.json
> chore: bump version to 0.17.0-dev.19

- src/commands/restart.js
- src/commands/start.js
- src/docker/DockerCompose.js
- src/docker/errors/ServiceIsNotRunningError.js
replace use of incorrect or obsolete terms in variable names and help output
clean up code and output
- replace masternode with node, since full nodes are also possible
- replace preset with network in one remaining function
tested with other PRs together
> fix: pass correct params to error message

- src/commands/platform/init.js
- src/commands/register.js
- src/commands/reset.js
- src/commands/restart.js
- src/commands/setup.js
- src/commands/start.js
- src/commands/stop.js
- src/commands/wallet/mint.js
- src/oclif/command/BaseCommand.js
Added verbose flag for every command
No
> feat: add verbose mode to every command

- package-lock.json
- package.json
Update Dash Pay contract to the recent one
Updated dashpay contract
With `platform:init`
None
> feat: update dashpay contract

- src/config/systemConfigs/systemConfigs.js
- templates/tenderdash/config.toml.template
This PR adds testnet system configs and bumps dapi and drive to release versions
This is required to allow community testnet masternodes to connect and sync
Add masternode config details taken from testnet masternode
> fix: update testnet systemConfigs

- package.json
Revert double release accidentally introduced in #233 
`package.json` had two versions
Removed the older version
Untested, how do I test it?
> chore: revert double release

- src/config/configOptionMigrations.js
- src/config/systemConfigs/systemConfigs.js
DashPay contract is not set for testnet config that leads to inconsistent (non-deterministic) validation result for `contactRequest` documents and incorrect block result error in the result.
Set DashPay contract ID and height for testnet config.
Implemented migration for previous configs.
Syncing node
None
> fix: DashPay contract is not set for testnet

- package-lock.json
- package.json
Update SDK to branch that uses async ST commits and acks
Updated SDK
Run bootstrap and platform-init
None
> chore: update sdk version

- package-lock.json
- package.json
- src/commands/reset.js
- src/commands/setup.js
- src/listr/tasks/platform/tenderdashInitTaskFactory.js
> chore: update SDK and bump a version

- package-lock.json
- package.json
> chore: update dash sdk to 3.18.0-dev.1

- package-lock.json
- package.json
> chore: bump version to v0.18.0-dev.5

- src/commands/reset.js
- src/listr/tasks/platform/tenderdashInitTaskFactory.js
> fix: reset task

- package-lock.json
- package.json
Bumped version
Unit tests
None
> chore: bump version to 0.18.0-dev.6

- package-lock.json
- package.json
Bumped version
Unit tests
None
> chore: bump version to 0.18.0-dev.7

- package-lock.json
- package.json
Bumped version
Unit tests
None
> chore: bump version to 0.18.0-dev.8

- src/config/configOptionMigrations.js
- src/config/systemConfigs/systemConfigs.js
- templates/tenderdash/config.toml.template
Update Tenderdash to 0.34.3
- Tenderdash docker image updated to 0.34.3
- Set `timeout_broadcast_tx_commit` to `10s`
- Set `timeout_commit` to `1s`
- `keep-invalid-txs-in-cache` set to `true`
None
Tenderdash < 0.34.3 is not supported
> feat!: update Tenderdash to 0.34.3

- src/config/systemConfigs/systemConfigs.js
dashd updated to 0.17.0.0-rc3-hotfix1
No
> feat: update dashd to 0.17.0.0-rc3-hotfix1

- package-lock.json
- package.json
> chore: update sdk to the newest version

- package-lock.json
- package.json
> chore: update sdk and bump version

- src/config/configOptionMigrations.js
Updating Drive and DAPI images to version 18 in migration file
- Updated migration file
None.
> feat: update Drive and DAPI images in migration file

- package-lock.json
- package.json
Updated version
Updated version
None
> chore: bump version to 0.19.0-dev.1

- src/commands/group/start.js
> feat: wait for tenderdash on start

- package-lock.json
- package.json
> chore: bump version to 0.19.0-dev.4

- src/core/waitForBlocks.js
- src/core/waitForConfirmations.js
- src/core/waitForCoreSync.js
`progressCallback not found` error thrown
- Add default value to `progressCallback` param in `waitCoreForSync` function
Running command
None
> fix: progressCallback not found

- package-lock.json
- package.json
Bump version
Bump version
None
> chore: bump version to 0.19.0-dev.7

- configs/system/base.js
Drive image updated up to 0.19-dev
> feat: update drive to 0.19-dev

- package-lock.json
- package.json
Bumped version
Unit tests
None
> chore: bump version to 0.19.0-dev.8

- src/listr/tasks/platform/waitForNodeToBeReadyTaskFactory.js
> chore: debug for travis

- package-lock.json
- package.json
Bumped version
Unit tests
None
> chore: bump version to 0.19.0-dev.9

- src/core/waitForCoreSync.js
- src/listr/tasks/platform/waitForNodeToBeReadyTaskFactory.js
- src/listr/tasks/registerMasternodeTaskFactory.js
- src/listr/tasks/setup/local/configureCoreTaskFactory.js
- src/listr/tasks/setup/local/initializePlatformTaskFactory.js
Invalid order of operations and waits fixed
- Updated `waitForCoreSync` to accept `rpcClient`
- Reordered operations
Local setup
None.
> fix: invalid order of operations lead to Drive to never start

- package-lock.json
- package.json
Bump version
Bump version
None.
> chore: bump version to 0.19.0-dev.10

- src/oclif/command/ConfigBaseCommand.js
- src/oclif/command/GroupBaseCommand.js
> fix: grammar in some error messages

- src/docker/DockerCompose.js
Now we check docker version
Manual
No
> feat: check docker version

- src/commands/group/start.js
- src/commands/start.js
- src/listr/tasks/setup/local/configureCoreTaskFactory.js
- src/listr/tasks/setup/local/initializePlatformTaskFactory.js
- src/listr/tasks/startNodeTaskFactory.js
`Await for` is used instead of `Wait for` in some task titles and descriptions. This is grammatically incorrect as await requires an object without preposition.
https://grammarist.com/usage/await-vs-wait/
Replaced `Await for` with `Wait for`
No tests needed as only strings have been changed.
None
> fix: grammar in task titles 

- configs/migrations.js
- configs/schema/configJsonSchema.js
- configs/system/base.js
- configs/system/local.js
- templates/platform/drive/tenderdash/config.toml.dot
For different environments, we need different empty block interval
- Made tenderdash empty blocks configurable with mn bootstrap config
- Running commands
None
> feat: tenderdash empty blocks configuration

- src/core/generateBlsKeys.js
- src/listr/tasks/setup/setupRegularPresetTaskFactory.js
> fix: BlsSignatures is not a function

- src/core/generateBlsKeys.js
- src/listr/tasks/setup/setupRegularPresetTaskFactory.js
Reverts dashevo/mn-bootstrap#318
> revert: fix `BlsSignatures is not a function`

- package-lock.json
- package.json
- src/commands/group/reset.js
- src/commands/group/restart.js
- src/commands/group/start.js
- src/commands/group/stop.js
- src/commands/platform/init.js
- src/commands/reset.js
- src/commands/restart.js
- src/commands/setup.js
- src/commands/start.js
- src/commands/stop.js
- src/commands/wallet/mint.js
Having elapsed time for tasks will be very helpful for debugging.
- Enabled elapsed time for Listr2 tasks
Running commands
None
> feat: display tasks elapsed time in verbose mode

- src/config/configOptionMigrations.js
- src/config/systemConfigs/systemConfigs.js
- templates/dashd.conf.template
Update mn-bootstrap to use Dash Core 0.17.0.0-rc4
Updated image version and modified config to use new syntax
Tested starting local node, correct image is used and no errors.
None
> feat: update to core 0.17.0.0-rc4

- README.md
- src/commands/group/start.js
- src/commands/setup.js
- src/commands/update.js
- src/listr/tasks/startNodeTaskFactory.js
A command to update Docker images defined in config instead of `update` option.
- Removed `update` option from `start` command
- Introduce `update` command
Running command
`update` option is not supported
> feat!: update command

- configs/system/base.js
Update DAPI to 0.19
- Updated DAPI docker image to 0.19-dev
None
None
> feat: update DAPI to 0.19

- configs/migrations.js
- configs/system/base.js
Core devs have released an updated hotfix build. This PR updates mn-bootstrap to use that build.
- Update default core image to `0.17.0.0-rc4-hotfix2`
Tested in mn-bootstrap, image works without errors
None
> chore: update dashd to 0.17.0.0-rc4-hotfix2

- configs/system/base.js
- package-lock.json
- package.json
- src/listr/tasks/setup/local/initializePlatformTaskFactory.js
To be able to on/off verification of LLMQ signatures and chain locks using Core, additional flag is added.
- updated `feature-flags-contract`
- registration of an additional flag
Local setup.
None.
> feat: enable `verifyLLMQSignaturesWithCore` flag

- package-lock.json
- package.json
Bump version to 0.19.0-dev.13
No
> chore: bump version to 0.19.0-dev.13

- bin/mn
- package-lock.json
- package.json
- src/core/wallet/importPrivateKey.js
> fix:  cannot read property 'toString' of undefined

- package-lock.json
- package.json
Bumped version to 0.19.0-dev.14
No
> chore: bump version to 0.19.0-dev.14

- src/core/wallet/importPrivateKey.js
> chore: remove console.log

- package-lock.json
- package.json
> chore: bump version to 0.19.0-dev.15

- package-lock.json
- package.json
> chore: bump version to 0.19.0-dev.16

- README.md
Upgrade docs were necessary in the case of platform resets. More detailed step-by-step instructions will be [added to the user docs](https://docs.dash.org/en/stable/masternodes/setup-testnet.html#masternode-installation) instead.
- Added steps to update node
tested on testnet
none
> docs: add update docs

- configs/migrations.js
- configs/system/base.js
- configs/system/testnet.js
Platform was wiped and redeployed for the v0.19 release. This PR contains updated contract IDs.
- Update testnet config with new contracts and genesis data
- Update image versions
- Testing local full node deploy
- All contracts changed
> chore: add v0.19 contracts

- configs/migrations.js
- configs/system/base.js
Core devs have released an updated build. This PR updates mn-bootstrap to use that build.
- Update default core image to `0.17.0.0-rc5`
Tested in mn-bootstrap, image works without errors
None
> chore: update dashd to 0.17.0.0-rc5

- CHANGELOG.md
- configs/migrations.js
- configs/system/base.js
- package-lock.json
- package.json
Bring changes from master to `v0.20-dev`
Pull changes
In CI
None
> chore: update dev branch with changes from master

- src/core/wallet/waitForBalanceToConfirm.js
- src/createDIContainer.js
- src/listr/tasks/registerMasternodeTaskFactory.js
- src/listr/tasks/wallet/generateToAddressTaskFactory.js
Using more than 4 nodes during setup raises bad-txns-premature-spend-of-coinbase error.
Changed the way how we control transactions in regtest mode. Instead of mining a lot of transactions, we wait for the balance to be confirmed.
Manually
No
> fix: bad-txns-premature-spend-of-coinbase error

- src/commands/setup.js
- src/listr/tasks/setup/setupLocalPresetTaskFactory.js
Enable debug output flag for a network created with `setup local`
- Add boolean `debug` flag
- Add step to query debug if not specified
- Set core and platform debug appropriately in config
Tested local and in CI
`setup local` command requests debug setting
> feat!: enable and request debug output for setup local

- configs/migrations.js
- configs/system/local.js
- docker-compose.platform.yml
- templates/platform/drive/tenderdash/config.toml.dot
Tenderdash peers are not connecting properly on local network.
- Disabled pex
- Allowed peers with the same IP
- List persistent peers as unconditional
- Brought empty block interval back to 3m
- Used the same ports inside container
Running setup command
None
> fix: tenderdash local connectivity issues

- configs/migrations.js
- configs/schema/configJsonSchema.js
- configs/system/base.js
- src/listr/tasks/setup/setupLocalPresetTaskFactory.js
- templates/platform/drive/tenderdash/config.toml.dot
We need to be able to control tenderdash log output using dashmate configs
Added `platform.drive.tenderdash.log.format` and `platform.drive.tenderdash.log.level` to schema with rules corresponding to tendermint documentation.
Tested locally
Should be covered by migration
> feat: configure tenderdash log level

- README.md
> docs: update readme: mn -> dashmate

- src/listr/tasks/setup/setupLocalPresetTaskFactory.js
Setup command sets miner interval to all nodes in the local network
- Make the line that sets the miner interval unconditional
Run the setup script
None
> fix: nodes are not able to sync mocked time

- bin/temporary_reset_script.sh
Add a temporary reset script, so all the devs have the same script.
*TO BE REMOVED AFTER RESET COMMAND REVISION*
Add a simple reset script
Run on the machine
None
> feat: add a temporary reset script for the local network

- configs/system/base.js
- templates/platform/drive/tenderdash/config.toml.dot
quorum_type should be set from config
- set quorum_type from config
- remove obsolete `llmq_type_used`
- update tenderdash to working version
- Tested working against tenderdash 0.4.2
Seems to break tenderdash 0.4.1, fixed in tenderdash 0.4.2
> fix: static quorum type in tenderdash config

- configs/migrations.js
- configs/system/base.js
`dashmate update` should be able to download minor Core updates
- Set less precise Core image `0.17`
- Update sentinel to 1.6.0
- Fix error in 0.19.1 migration
Tested migration from master to this branch by incrementing package version
None
> feat: support minor Core updates

- README.md
Fix typo in readme docs
Add `up -d` to docker-compose example command
Untested
None
> docs: fix docker-compose typo

- package-lock.json
- package.json
The version was bumped to 0.20.0-dev.5
> chore(release): bump version to 0.20.0-dev.5

- package-lock.json
- package.json
The version bumped to 0.20.0-dev.6
No
> chore: bump version to 0.20.0-dev.6

- package.json
- src/docker/DockerCompose.js
- src/listr/tasks/buildServicesTaskFactory.js
- src/listr/tasks/startGroupNodesTaskFactory.js
- src/listr/tasks/startNodeTaskFactory.js
- src/oclif/command/BaseCommand.js
Use Docker BuildKit to build DAPI and Drive images in order to utilize efficient caching mechanisms.
- Introduced `DOCKER_COMPOSE_V2` env variable to enable compose v2 (necessary for images built with BuildKit)
- Use BuildKit to build images
- Remove copy NPM cache task
With Drive and DAPI CIs
Building services from path required compose v2 installed and `DOCKER_COMPOSE_V2` env to set
> feat!: efficient service build cache

- package-lock.json
- package.json
Need to bump version to make a new release
The version was bumped to 0.20.0-dev.7
By running agains platform test suite
None
> chore: bump version to 0.20.0-dev.7

- configs/system/base.js
Tenderdash 0.5.5 was released
- Use Tenderdash 0.5.5 in base config
On palinka
Not compatible with older versions of Tenderdash
> chore: update tenderdash version to 0.5.5

- src/listr/tasks/setup/local/initializePlatformTaskFactory.js
Remove `verifyLLMQSignaturesWithCore` feature flag since legacy logic is removed from Drive
- Don't activate `verifyLLMQSignaturesWithCore` feature flag 
None
`verifyLLMQSignaturesWithCore` feature flag is not activating anymore
> chore: remove `verifyLLMQSignaturesWithCore` feature flag

- configs/migrations.js
- configs/system/base.js
- configs/system/testnet.js
- package-lock.json
- package.json
Testnet was redeployed, so contract IDs and other variables needed to be updated
Updated contracts, image versions, nodes and migrations.
On testnet
> chore: update to testnet-3

- CHANGELOG.md
- package-lock.json
- package.json
Release Dashmate v0.20.0
- updated changelog
- bump version
None
None
> chore(release): update changelog and version to v0.20.0

- CHANGELOG.md
- package-lock.json
- package.json
Release 0.20.1
- Update changelog
- Bump version to 0.20.1
None
None
> chore(release): update changelog and bump version 0.20.1

- configs/migrations.js
- configs/system/testnet.js
Testnet chain halted, so it was necessary to redeploy with new parameters
- Update parameters
Locally against current testnet
Will no longer be able to connect to networks prior to `dash-testnet-5`
> chore: contract and package updates for 0.20.2
